
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      # Used for jwt access token 
      ACCESS_TOKEN_NAME: access_token
      ACCESS_TOKEN_SECRET: dummy_access_token

      # Used for jwt refresh token
      REFRESH_TOKEN_NAME: refresh_token
      REFRESH_TOKEN_SECRET: dummy_refresh_token

      # Used for password hashing
      SALT_LENGTH: 16
    ports:
      - 3000:3000
